name: deploy on push
on: [push]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key            
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug SSH directory      
        run: |
          echo ">>> ls ~/.ssh <<<"
          ls -la ~/.ssh || true
          echo ">>> secret length <<<"
          echo -n "${{ secrets.SSH_KEY }}" | wc -c

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Clean remote directory
        run: |
          ssh -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            ${{ secrets.SSH_USER_NAME }}@${{ secrets.HOST }} \
            "rm -rf /var/www/html/*"

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key_path: ~/.ssh/id_rsa
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1
          